---
- hosts: all
  tasks:
  - name: make some space
    command: find -name '*-*' -mtime +7 -delete
    args:
      chdir: /var/log
    changed_when: false

  - name: remove old packages
    command: apt-get clean
    check_mode: false
    changed_when: false

  - name: remove indexes
    shell: rm -r /var/lib/apt/lists/*
    check_mode: false
    changed_when: false
    failed_when: false
